name: fibertools
channels:
    - conda-forge
    - bioconda
    - defaults
dependencies:
    - sphinx==4.2.0
    - docutils==0.17
    - rstcheck==5.0.0
    - numba>=0.53
    - pandas>=1.4
    - numpy>=1.22
    - pysam>=0.19.0
    - pyranges>=0.0.115
    - mokapot==0.8
    - scikit-learn
    - xgboost>=1.5.1
    #- python>=3.10 # needed by cgranges
    #- cgranges
    - Cython
    - pip>=20.1 # pip is needed as dependency
    - pip:
          - sphinx_rtd_theme
          - readthedocs-sphinx-search
          - polars>=0.13
          - pyd4
